# Generated by Django 4.2.1 on 2023-11-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manage_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('winning_amount', models.IntegerField(max_length=12)),
                ('cost', models.IntegerField(max_length=2)),
            ],
        ),
    ]
