# Generated by Django 4.2.1 on 2023-11-03 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPSApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage_ticket',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='manage_ticket',
            name='winning_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9999999999.99)]),
        ),
    ]
