# Generated by Django 4.2.1 on 2023-11-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LPSApp', '0002_alter_manage_ticket_cost_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manage_Ticket',
            new_name='Ticket',
        ),
    ]
