# Generated by Django 4.2.3 on 2023-11-15 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPSApp', '0003_rename_manage_ticket_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Name must only contain letters, numbers, and spaces.', regex='^[a-zA-Z0-9 ]+$')]),
        ),
    ]
