# Generated by Django 4.2.1 on 2023-11-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPSApp', '0005_ticket_next_draw_date_ticket_powerball_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='next_draw_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='powerball',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='previous_draw_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='previuous_draw_number_1',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='previuous_draw_number_2',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='previuous_draw_number_3',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='previuous_draw_number_4',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='previuous_draw_number_5',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='previuous_draw_number_6',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
