# Generated by Django 4.2.1 on 2023-11-22 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LPSApp', '0006_alter_ticket_next_draw_date_alter_ticket_powerball_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='next_draw_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='previous_draw_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
