# Generated by Django 4.2.1 on 2023-11-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPSApp', '0007_alter_ticket_next_draw_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
