# Generated by Django 4.2.3 on 2023-12-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPSApp', '0010_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ticket',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ticketCost',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
