# Generated by Django 4.2.3 on 2023-12-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPSApp', '0012_order_number_1_order_number_2_order_number_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='number_6',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='previuous_draw_number_6',
        ),
        migrations.AddField(
            model_name='order',
            name='winner',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
