# Generated by Django 4.2.3 on 2023-12-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPSApp', '0014_remove_ticket_powerball_order_winning_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='claimed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
