# Generated by Django 4.2.3 on 2023-12-03 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LPSApp', '0017_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='next_draw_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='previous_draw_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
