# Generated by Django 4.2.3 on 2023-12-05 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LPSApp', '0020_userprofile_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='claimed',
        ),
        migrations.CreateModel(
            name='OrderClaimed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed', models.BooleanField(default=False, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_status', to='LPSApp.order')),
            ],
        ),
    ]
