# Generated by Django 4.2.3 on 2023-12-05 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LPSApp', '0021_remove_order_claimed_orderclaimed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderClaimed',
            new_name='ClaimedOrder',
        ),
    ]
