# Generated by Django 4.2.3 on 2023-12-05 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LPSApp', '0022_rename_orderclaimed_claimedorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='previuous_draw_number_1',
            new_name='previous_draw_number_1',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='previuous_draw_number_2',
            new_name='previous_draw_number_2',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='previuous_draw_number_3',
            new_name='previous_draw_number_3',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='previuous_draw_number_4',
            new_name='previous_draw_number_4',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='previuous_draw_number_5',
            new_name='previous_draw_number_5',
        ),
    ]
