# Generated by Django 4.2.3 on 2023-12-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPSApp', '0023_rename_previuous_draw_number_1_ticket_previous_draw_number_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='claimed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
