# Generated by Django 4.2.3 on 2023-12-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LPSApp', '0024_order_claimed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClaimedOrder',
        ),
    ]
