# Generated by Django 4.2.3 on 2023-12-05 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LPSApp', '0025_delete_claimedorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previouswinner',
            old_name='ticketType',
            new_name='ticket_type',
        ),
    ]
