# Generated by Django 5.0.7 on 2024-10-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPSApp', '0026_rename_tickettype_previouswinner_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcard',
            name='expiration_date',
            field=models.CharField(max_length=225),
        ),
    ]
