# Generated by Django 5.0.7 on 2024-10-25 04:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPSApp', '0027_alter_savedcard_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcard',
            name='expiration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
